# This file was generated by GoReleaser. DO NOT EDIT.
cask "paddock" do
  name "paddock"
  desc "Short description of your tool"
  homepage "https://github.com/eepzii/paddock"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paddock"

  on_macos do
    on_intel do
      url "https://github.com/eepzii/paddock/releases/download/v#{version}/paddock_Darwin_x86_64.tar.gz"
      sha256 "3c5c19f60249b89ff619cff7abc0a75261673b289d78325457f5b576be95c34c"
    end
    on_arm do
      url "https://github.com/eepzii/paddock/releases/download/v#{version}/paddock_Darwin_arm64.tar.gz"
      sha256 "93138aef0c14bf7c7e365c8228ca2e5e07f0ba65c5afaaa88c607a1f216576c7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/eepzii/paddock/releases/download/v#{version}/paddock_Linux_x86_64.tar.gz"
      sha256 "b2494fb3d837e9c03d3443729a7af9a65f61da9ab29753f40624078ad502f9ac"
    end
    on_arm do
      url "https://github.com/eepzii/paddock/releases/download/v#{version}/paddock_Linux_arm64.tar.gz"
      sha256 "2e1368cadeacc83887bdfce998a812006e9aa2be8842032b1c1704b27ff57afe"
    end
  end

  # No zap stanza required
end
